<template>
	<el-card>
		<h4>ISO 语言代码</h4>
		<p>HTML 的 lang 属性可用于网页或部分网页的语言。这对搜索引擎和浏览器是有帮助的。</p>
		<p>根据 W3C 推荐标准，您应该通过 &lt;html&gt; 标签中的 lang 属性对每张页面中的主要语言进行声明，比如：</p>
		<el-input type="textarea" :autosize="istrue" style="width: 60%;" :readonly="istrue" v-model="text1"></el-input>
		<p>在 XHTML 中，采用如下方式在 &lt;html&gt; 标签中对语言进行声明：</p>
		<el-input type="textarea" :autosize="istrue" style="width: 60%;" :readonly="istrue" v-model="text2"></el-input>
		<el-divider></el-divider>
		<h4>ISO 639-1 语言代码</h4>
		<p>ISO 639-1 为各种语言定义了缩略词。您可以在 HTML 和 XHTML 中的 lang 和 xml:lang 属性中使用它们。</p>
		<table class="el-table">
			<tbody>
				<tr>
					<th style="width:50%;">Language</th>
					<th>ISO Code</th>
				</tr>
				<tr>
					<td>Abkhazian</td>
					<td>ab</td>
				</tr>
				<tr>
					<td>Afar</td>
					<td>aa</td>
				</tr>
				<tr>
					<td>Afrikaans</td>
					<td>af</td>
				</tr>
				<tr>
					<td>Albanian</td>
					<td>sq</td>
				</tr>
				<tr>
					<td>Amharic</td>
					<td>am</td>
				</tr>
				<tr>
					<td>Arabic</td>
					<td>ar</td>
				</tr>
				<tr>
					<td>Armenian</td>
					<td>hy</td>
				</tr>
				<tr>
					<td>Assamese</td>
					<td>as</td>
				</tr>
				<tr>
					<td>Aymara</td>
					<td>ay</td>
				</tr>
				<tr>
					<td>Azerbaijani</td>
					<td>az</td>
				</tr>
				<tr>
					<td>Bashkir</td>
					<td>ba</td>
				</tr>
				<tr>
					<td>Basque</td>
					<td>eu</td>
				</tr>
				<tr>
					<td>Bengali (Bangla)</td>
					<td>bn</td>
				</tr>
				<tr>
					<td>Bhutani</td>
					<td>dz</td>
				</tr>
				<tr>
					<td>Bihari</td>
					<td>bh</td>
				</tr>
				<tr>
					<td>Bislama</td>
					<td>bi</td>
				</tr>
				<tr>
					<td>Breton</td>
					<td>br</td>
				</tr>
				<tr>
					<td>Bulgarian</td>
					<td>bg</td>
				</tr>
				<tr>
					<td>Burmese</td>
					<td>my</td>
				</tr>
				<tr>
					<td>Byelorussian (Belarusian)</td>
					<td>be</td>
				</tr>
				<tr>
					<td>Cambodian</td>
					<td>km</td>
				</tr>
				<tr>
					<td>Catalan</td>
					<td>ca</td>
				</tr>
				<tr>
					<td>Cherokee</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Chewa</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Chinese (Simplified)</td>
					<td>zh</td>
				</tr>
				<tr>
					<td>Chinese (Traditional)</td>
					<td>zh</td>
				</tr>
				<tr>
					<td>Corsican</td>
					<td>co</td>
				</tr>
				<tr>
					<td>Croatian</td>
					<td>hr</td>
				</tr>
				<tr>
					<td>Czech</td>
					<td>cs</td>
				</tr>
				<tr>
					<td>Danish</td>
					<td>da</td>
				</tr>
				<tr>
					<td>Divehi</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Dutch</td>
					<td>nl</td>
				</tr>
				<tr>
					<td>Edo</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>English</td>
					<td>en</td>
				</tr>
				<tr>
					<td>Esperanto</td>
					<td>eo</td>
				</tr>
				<tr>
					<td>Estonian</td>
					<td>et</td>
				</tr>
				<tr>
					<td>Faeroese</td>
					<td>fo</td>
				</tr>
				<tr>
					<td>Farsi</td>
					<td>fa</td>
				</tr>
				<tr>
					<td>Fiji</td>
					<td>fj</td>
				</tr>
				<tr>
					<td>Finnish</td>
					<td>fi</td>
				</tr>
				<tr>
					<td>Flemish</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>French</td>
					<td>fr</td>
				</tr>
				<tr>
					<td>Frisian</td>
					<td>fy</td>
				</tr>
				<tr>
					<td>Fulfulde</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Galician</td>
					<td>gl</td>
				</tr>
				<tr>
					<td>Gaelic (Scottish)</td>
					<td>gd</td>
				</tr>
				<tr>
					<td>Gaelic (Manx)</td>
					<td>gv</td>
				</tr>
				<tr>
					<td>Georgian</td>
					<td>ka</td>
				</tr>
				<tr>
					<td>German</td>
					<td>de</td>
				</tr>
				<tr>
					<td>Greek</td>
					<td>el</td>
				</tr>
				<tr>
					<td>Greenlandic</td>
					<td>kl</td>
				</tr>
				<tr>
					<td>Guarani</td>
					<td>gn</td>
				</tr>
				<tr>
					<td>Gujarati</td>
					<td>gu</td>
				</tr>
				<tr>
					<td>Hausa</td>
					<td>ha</td>
				</tr>
				<tr>
					<td>Hawaiian</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Hebrew</td>
					<td>he, iw</td>
				</tr>
				<tr>
					<td>Hindi</td>
					<td>hi</td>
				</tr>
				<tr>
					<td>Hungarian</td>
					<td>hu</td>
				</tr>
				<tr>
					<td>Ibibio</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Icelandic</td>
					<td>is</td>
				</tr>
				<tr>
					<td>Igbo</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Indonesian</td>
					<td>id, in</td>
				</tr>
				<tr>
					<td>Interlingua</td>
					<td>ia</td>
				</tr>
				<tr>
					<td>Interlingue</td>
					<td>ie</td>
				</tr>
				<tr>
					<td>Inuktitut</td>
					<td>iu</td>
				</tr>
				<tr>
					<td>Inupiak</td>
					<td>ik</td>
				</tr>
				<tr>
					<td>Irish</td>
					<td>ga</td>
				</tr>
				<tr>
					<td>Italian</td>
					<td>it</td>
				</tr>
				<tr>
					<td>Japanese</td>
					<td>ja</td>
				</tr>
				<tr>
					<td>Javanese</td>
					<td>jv</td>
				</tr>
				<tr>
					<td>Kannada</td>
					<td>kn</td>
				</tr>
				<tr>
					<td>Kanuri</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Kashmiri</td>
					<td>ks</td>
				</tr>
				<tr>
					<td>Kazakh</td>
					<td>kk</td>
				</tr>
				<tr>
					<td>Kinyarwanda (Ruanda)</td>
					<td>rw</td>
				</tr>
				<tr>
					<td>Kirghiz</td>
					<td>ky</td>
				</tr>
				<tr>
					<td>Kirundi (Rundi)</td>
					<td>rn</td>
				</tr>
				<tr>
					<td>Konkani</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Korean</td>
					<td>ko</td>
				</tr>
				<tr>
					<td>Kurdish</td>
					<td>ku</td>
				</tr>
				<tr>
					<td>Laothian</td>
					<td>lo</td>
				</tr>
				<tr>
					<td>Latin</td>
					<td>la</td>
				</tr>
				<tr>
					<td>Latvian (Lettish)</td>
					<td>lv</td>
				</tr>
				<tr>
					<td>Limburgish ( Limburger)</td>
					<td>li</td>
				</tr>
				<tr>
					<td>Lingala</td>
					<td>ln</td>
				</tr>
				<tr>
					<td>Lithuanian</td>
					<td>lt</td>
				</tr>
				<tr>
					<td>Macedonian</td>
					<td>mk</td>
				</tr>
				<tr>
					<td>Malagasy</td>
					<td>mg</td>
				</tr>
				<tr>
					<td>Malay</td>
					<td>ms</td>
				</tr>
				<tr>
					<td>Malayalam</td>
					<td>ml</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Maltese</td>
					<td>mt</td>
				</tr>
				<tr>
					<td>Maori</td>
					<td>mi</td>
				</tr>
				<tr>
					<td>Marathi</td>
					<td>mr</td>
				</tr>
				<tr>
					<td>Moldavian</td>
					<td>mo</td>
				</tr>
				<tr>
					<td>Mongolian</td>
					<td>mn</td>
				</tr>
				<tr>
					<td>Nauru</td>
					<td>na</td>
				</tr>
				<tr>
					<td>Nepali</td>
					<td>ne</td>
				</tr>
				<tr>
					<td>Norwegian</td>
					<td>no</td>
				</tr>
				<tr>
					<td>Occitan</td>
					<td>oc</td>
				</tr>
				<tr>
					<td>Oriya</td>
					<td>or</td>
				</tr>
				<tr>
					<td>Oromo (Afan, Galla)</td>
					<td>om</td>
				</tr>
				<tr>
					<td>Papiamentu</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Pashto (Pushto)</td>
					<td>ps</td>
				</tr>
				<tr>
					<td>Polish</td>
					<td>pl</td>
				</tr>
				<tr>
					<td>Portuguese</td>
					<td>pt</td>
				</tr>
				<tr>
					<td>Punjabi</td>
					<td>pa</td>
				</tr>
				<tr>
					<td>Quechua</td>
					<td>qu</td>
				</tr>
				<tr>
					<td>Rhaeto-Romance</td>
					<td>rm</td>
				</tr>
				<tr>
					<td>Romanian</td>
					<td>ro</td>
				</tr>
				<tr>
					<td>Russian</td>
					<td>ru</td>
				</tr>
				<tr>
					<td>Sami (Lappish)</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Samoan</td>
					<td>sm</td>
				</tr>
				<tr>
					<td>Sangro</td>
					<td>sg</td>
				</tr>
				<tr>
					<td>Sanskrit</td>
					<td>sa</td>
				</tr>
				<tr>
					<td>Serbian</td>
					<td>sr</td>
				</tr>
				<tr>
					<td>Serbo-Croatian</td>
					<td>sh</td>
				</tr>
				<tr>
					<td>Sesotho</td>
					<td>st</td>
				</tr>
				<tr>
					<td>Setswana</td>
					<td>tn</td>
				</tr>
				<tr>
					<td>Shona</td>
					<td>sn</td>
				</tr>
				<tr>
					<td>Sindhi</td>
					<td>sd</td>
				</tr>
				<tr>
					<td>Sinhalese</td>
					<td>si</td>
				</tr>
				<tr>
					<td>Siswati</td>
					<td>ss</td>
				</tr>
				<tr>
					<td>Slovak</td>
					<td>sk</td>
				</tr>
				<tr>
					<td>Slovenian</td>
					<td>sl</td>
				</tr>
				<tr>
					<td>Somali</td>
					<td>so</td>
				</tr>
				<tr>
					<td>Spanish</td>
					<td>es</td>
				</tr>
				<tr>
					<td>Sundanese</td>
					<td>su</td>
				</tr>
				<tr>
					<td>Swahili (Kiswahili)</td>
					<td>sw</td>
				</tr>
				<tr>
					<td>Swedish</td>
					<td>sv</td>
				</tr>
				<tr>
					<td>Syriac</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Tagalog</td>
					<td>tl</td>
				</tr>
				<tr>
					<td>Tajik</td>
					<td>tg</td>
				</tr>
				<tr>
					<td>Tamazight</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Tamil</td>
					<td>ta</td>
				</tr>
				<tr>
					<td>Tatar</td>
					<td>tt</td>
				</tr>
				<tr>
					<td>Telugu</td>
					<td>te</td>
				</tr>
				<tr>
					<td>Thai</td>
					<td>th</td>
				</tr>
				<tr>
					<td>Tibetan</td>
					<td>bo</td>
				</tr>
				<tr>
					<td>Tigrinya</td>
					<td>ti</td>
				</tr>
				<tr>
					<td>Tonga</td>
					<td>to</td>
				</tr>
				<tr>
					<td>Tsonga</td>
					<td>ts</td>
				</tr>
				<tr>
					<td>Turkish</td>
					<td>tr</td>
				</tr>
				<tr>
					<td>Turkmen</td>
					<td>tk</td>
				</tr>
				<tr>
					<td>Twi</td>
					<td>tw</td>
				</tr>
				<tr>
					<td>Uighur</td>
					<td>ug</td>
				</tr>
				<tr>
					<td>Ukrainian</td>
					<td>uk</td>
				</tr>
				<tr>
					<td>Urdu</td>
					<td>ur</td>
				</tr>
				<tr>
					<td>Uzbek</td>
					<td>uz</td>
				</tr>
				<tr>
					<td>Venda</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Vietnamese</td>
					<td>vi</td>
				</tr>
				<tr>
					<td>Volapuk</td>
					<td>vo</td>
				</tr>
				<tr>
					<td>Welsh</td>
					<td>cy</td>
				</tr>
				<tr>
					<td>Wolof</td>
					<td>wo</td>
				</tr>
				<tr>
					<td>Xhosa</td>
					<td>xh</td>
				</tr>
				<tr>
					<td>Yi</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>Yiddish</td>
					<td>yi, ji</td>
				</tr>
				<tr>
					<td>Yoruba</td>
					<td>yo</td>
				</tr>
				<tr>
					<td>Zulu</td>
					<td>zu</td>
				</tr>
			</tbody>
		</table>
	</el-card>
</template>

<script>
	export default {
		data() {
			return {
				istrue: true,
				text1: '<html lang="en">\n...\n</html>\n',
				text2: '<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">\n...\n</html>\n'
			}
		}
	}
</script>

<style scoped="scoped">
	th,td{
		border-top: 1px #EBEEF5 solid;
		border-bottom: 1px #EBEEF5 solid;
	}
</style>
